#!/usr/bin/perl -w
#
# (C) Copyright 2004 Christian Hofstaedtler
#

my $func_prefix = "DL_";

my $file_in;
my $file_out_c;
my $file_out_h;

my $status = 0;

$file_in = shift(@ARGV) or ($status = 1);
$file_out_c = shift(@ARGV) or ($status = 2);
$file_out_h = shift(@ARGV) or ($status = 3);
if ($file_out_c eq $file_out_h) { $status = 10; }
if ($file_out_c eq $file_in) { $status = 10; }
if ($file_out_h eq $file_in) { $status = 10; }

if ($status)
{
	print "usage: $0 input-list output.c output.h\n";
	exit $status;
}

my $line = 0;

my $api_name = "";
my $api_ret = "";
my $api_exposedp = "";
my $api_passp = "";

my $started = 0;

open(INPUTLIST,"<".$file_in);
open(OUTPUTC,">".$file_out_c);
open(OUTPUTH,">".$file_out_h);
while(<INPUTLIST>)
{
	$_ =~ s/\n//;
	if (/^\/\//) 
	{
		print OUTPUTC $_."\n"; 
		print OUTPUTH $_."\n";
		next; 
	}
	if (!$started)
	{
		print OUTPUTC "\n";
		print OUTPUTC "// WARNING: DO NOT EDIT THIS FILE DIRECTLY\n";
		print OUTPUTC "// THIS FILE IS AUTOGENERATED, YOUR CHANGES WILL BE LOST\n";
		print OUTPUTC "#include <unistd.h>\n#include <stdio.h>\n#include <errno.h>\n#include <stdlib.h>\n";
		print OUTPUTC "#define N_PLAT_NLM\n#include <nwadv.h>\n#include <nwthread.h>\n\n";

		print OUTPUTH "\n";
		print OUTPUTH "// WARNING: DO NOT EDIT THIS FILE DIRECTLY\n";
		print OUTPUTH "// THIS FILE IS AUTOGENERATED, YOUR CHANGES WILL BE LOST\n";
		print OUTPUTH "#include <unistd.h>\n#include <stdio.h>\n#include <errno.h>\n#include <stdlib.h>\n";
		print OUTPUTH "#define N_PLAT_NLM\n#include <nwadv.h>\n#include <nwthread.h>\n\n";

		print OUTPUTH "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n";
		
		$started = 1;
	}
	if (/^#/) 
	{ 
		print OUTPUTC $_."\n"; 
		print OUTPUTH "// ".$_."\n";
		next; 
	}

	if ($line == 0)
	{	$api_name = $_; }
	if ($line == 1)
	{	$api_ret = $_;	}
	if ($line == 2)
	{	$api_exposedp = $_; }
	if ($line == 3)
	{	$api_passp = $_; }
	
	$line++;
	if ($line == 4)
	{
		$line = 0; 
		print OUTPUTC "$api_ret $func_prefix$api_name ($api_exposedp)\n";
		print OUTPUTC "{\n";
		print OUTPUTC "\t$api_ret (*dynaload_$api_name) ($api_exposedp);\n";
		print OUTPUTC "\t$api_ret dynaloadReturnValue;\n";
		print OUTPUTC "\tdynaload_$api_name = ImportSymbol(GetNLMHandle(),\"$api_name\");\n";
		print OUTPUTC "\tif (dynaload_$api_name == NULL)\n";
		print OUTPUTC "\t\treturn NULL; // symbol not found, sorry!\n";
		print OUTPUTC "\tdynaloadReturnValue = (*dynaload_$api_name) ($api_passp);\n";
		print OUTPUTC "\tUnimportSymbol(GetNLMHandle(),\"$api_name\");\n";
		print OUTPUTC "\treturn dynaloadReturnValue;\n";
		print OUTPUTC "}\n";

		print OUTPUTH "extern $api_ret $func_prefix$api_name ($api_exposedp);\n";
		
		#print "inline $api_ret $api_name ($api_exposedp) $api_passp\n";
		$api_ret = $api_name = $api_exposedp = $api_passp = "";
	}
	
}

print OUTPUTH "\n#ifdef __cplusplus\n} // extern C\n#endif\n";

close INPUTLIST;
close OUTPUTC;
close OUTPUTH;

