Mime-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 7bit
Content-Disposition: inline
Subject: MailFilter/ax Problem Report

MailFilter/ax verification failed on the mail specified below. Reason:
%R

- From: "%f"
- To: "%t"
- Subject: "%s"

Probably you are the only one, who has been notified! Please take 
approaite actions, e.g. inform the sender and/or the recipient 
of the original mail.

The message (file) handle was:
%F

Regards,
MailFilter/ax %V @ %S.


