Mime-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 7bit
Content-Disposition: inline
Subject: MailFilter/ax Problem Report

MailFilter/ax scans Incoming and Outgoing E-Mails for e.g. Viruses.
You are getting this Problem Report because one of the scanned mails
from or to you got dropped. The message has been saved, but you will have to
contact your System Administrator to read the message in suspicion.

Cause of the drop: 
%R

Original Mail Information:
- From: "%f"
- To: "%t"
- Subject: "%s"

Please contact your Administrator (%P).

Administrative Information:
"%F"

Regards,
MailFilter/ax @ %S.

http://www.mailfilter.cc/en/

Please do NOT reply to this e-mail, it was sent from an unmonitored address.
