MAIL FROM:%M
RCPT TO:%P
From: %M
To: %P
Subject: MailFilter/ax MailCopy
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="==MFMFMFMFMF%U"

--==MFMFMFMFMF%U
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

Attached is the requested mail duplicate.

MailFilter/ax %V @ %S.

--==MFMFMFMFMF%U
Content-Type: message/rfc822

%X


