Mime-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 7bit
Content-Disposition: inline
Subject: MailFilter/ax Problem Report

MailFilter/ax has scanned an E-Mail you sent to %t,
and has detected that either the contents or an attachment is forbidden 
by the organizational policy.

Please contact either the origial recipient or the
Postmaster %P.

Details:
- From: "%f"
- To: "%t"
- Subject: "%s"

MailFilter/ax automated mail-scanning.
http://www.mailfilter.cc/en/

Please do NOT reply to this e-mail, it was sent from an unmonitored address.

