
../MailFilter/out/mfconfig.nlm: MFConfig.o MFConfig.def MFCONFIG.XDC ../MailFilter/out/pcre-nw.lib
	mwldnlm -sym off -nozerobss -o ../MailFilter/out/mfconfig.nlm MFConfig.def MFConfig.o MFCONFIG.XDC ../MailFilter/out/pcre-nw.lib ../MailFilter/out/pcreposix-nw.lib o:/ndk/clib/imports/clib.imp o:/ndk/clib/imports/clibpre.o o:/ndk/nwsnut/nwsdk/imports/nwsnut.imp
	ls -lah ../MailFilter/out/mfconfig.nlm


MFConfig.o: MFConfig.c
	mwccnlm -c -O2 -sym off -ir ..\\MailFilter\\Libs\\pcre MFConfig.c

clean:
	rm -f MFConfig.o core err.txt ../MailFilter/out/mfconfig.nlm

